# Generated by Django 5.2 on 2025-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_core', '0004_movie_streaming_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, to='movies_core.genre'),
        ),
    ]
