# Generated by Django 5.2 on 2025-05-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_core', '0005_userprofile_favorite_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
    ]
