"""Add poster_url column to Movie model

Revision ID: dd3f299d6f27
Revises: 
Create Date: 2025-05-06 08:03:43.074540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3f299d6f27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('plot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('plot')
        batch_op.drop_column('poster_url')

    # ### end Alembic commands ###
